### ISSUE TITLE
US-0002: Preço propriedade.

### ISSUE THREAD

**Issue by pedroLSoares** [Icaro-Salgado/w5g6-desafio-quality#9]
Indicar o preço dessa mesma propriedade com base na área total. Lembre-se que os preços por metro quadrado são determinados em função do  bairro.

- [x] Testes Unitários
- [ ] Testes de integração 
- [x] Implementação

**Comment by Icaro-Salgado** [comment]
> Indicar o preço dessa mesma propriedade com base na área total

### Controller
- [ ] Rota que recebe o ID da propriedade e retorna o valor da propriedade (#16)
- [ ] Retornar um PropertyValueDTO (#16)

### Service
	
- [ ] Calcular preço da propriedade _(recebe o ID da propriedade)_. (#17)
    > Preço total = Área da propriedade (m2) * Valor do m2 quadrado no bairro (#17)
- [ ] Buscar o bairro da propriedade (#17)
- [ ] Calcular a área da propriedade (Requisito 01) (#17)
- [ ] Retornar o cálculo (#17)

### Testes (Calcula preço da propriedade)
- [ ] Verificar se o calculo do valor total está correto  (#18)
- [ ] Verificar o que acontece se eu passo o ID null  (#18)
- [ ] Verificar o retorno para um caso de um ID não encontrado. (#18)
